image: ubuntu:20.04

stages:
- build
- test

before_script:
  - apt-get update -y && apt-get install -y curl
  - curl -sSLf https://scala-cli.virtuslab.org/get | sh
  - sudo chmod +x cs
  - sudo mv cs /usr/local/bin/scala-cli
  - scala-cli setup

build-job:
  stage: build
  script:
    - scala-cli --power package . --server=false --jvm system --force -o wacc-compiler

test-job:
  stage: test
  script:
    - scala-cli test .