image: ubuntu:20.04

stages:
- build
- test

build-job:
  stage: build
  script:
    - scala-cli --power package . --server=false --jvm system --force -o wacc-compiler

test-job:
  stage: test
  script:
    - scala-cli test .