image: ubuntu:20.04

stages:
- build
- test

before_script:
  - apt-get update -y && apt-get install -y curl
  - apt-get install -y openjdk-11-jdk
  - java -version
  - curl -sSLf https://scala-cli.virtuslab.org/get | sh
  - source ~/.profile

build-job:
  stage: build
  script:
    - scala-cli --power package . --server=false --jvm system --force -o wacc-compiler

test-job:
  stage: test
  script:
    - scala-cli test .