//> using scala 2.13
//> using platform jvm

// dependencies
//> using dep com.github.j-mie6::parsley::5.0.0-M2
//> using test.dep org.scalatest::scalatest::3.2.17

// these are all sensible defaults to catch annoying issues
//> using options -deprecation -unchecked -feature
//> using options -Xlint:nullary-unit -Xlint:infer-any -Xlint:unused -Xlint:nonlocal-return
//> using options -Wdead-code -Wextra-implicit -Wnumeric-widen

// these will help ensure you have access to the latest parsley releases
// even before they land on maven proper, or snapshot versions, if necessary.
// just in case they cause problems, however, keep them turned off unless you
// specifically need them.
// using repositories sonatype-s01:releases
// using repositories sonatype-s01:snapshots

// this is the filename generated by the package command
//> using packaging.output wacc-compiler
// this is the type of packaging done:
//   * bootstrap: will generate a light-weight jar that downloads dependencies on first run
//   * assembly: will generate a "FAT" jar that has the dependencies baked in (downloaded during build)
//   * native: will generate a native binary with scala-native (this requires platform native above)
// since LabTS will download dependencies to build anyway, bootstrap works fine -- assembly might be
// a tiny bit faster? native will have no start-up time, which may be an advantage, but your code may
// not compile with scala-native properly depending on what underlying Java code you've (indirectly)
// used.
//> using packaging.packageType bootstrap

// these are flags used by Scala native: if you aren't using scala-native, then they do nothing
// lto-thin has decent linking times, and release-fast does not too much optimisation.
//> using nativeLto thin
//> using nativeGc commix
//> using nativeMode release-fast
